### ISSUE TITLE
GitIgnore - Mac O/S

### ISSUE THREAD

**Issue by jwood36** [MinZhong7/Task-1_UML#5]
Add an exclusion for '.DS_Store' file(s)

refer to: https://stackoverflow.com/a/107921/659246

**Comment by MinZhong7** [comment]
I added .gitignor files, using the link you gave me, to the root and each folder where .DS_Store files exist. You can check my four commits of GitIgnore - Mac O/S #5 Issue. But I don't know why only one .gitignore file appears at the root. Then I remove the .DS_Store files from the repository.
