### ISSUE TITLE
Source - ReadMe.md

### ISSUE THREAD

**Issue by jwood36** [MinZhong7/Task-1_UML#7]
Readme.md File does not contain an explanation of the documents contained within the 'src' folder.

Per instructions:
> Unlike the [root] variant, this one will be an explanation of the Source Code, Folder Structure(s), Java SDK Version, IDE, Class Diagram (UML), etc.

**Comment by MinZhong7** [comment]
Added a Readme.md File contains an explanation of the documents contained within the 'src' folder.
