### ISSUE TITLE
UML - Design

### ISSUE THREAD

**Issue by jwood36** [MinZhong7/Task-1_UML#9]
Each Page should represent One of the types you have Chosen for your Design Model; in your case you have chosen the 'Type' Model, so each Page should be a representation of that 'Type'

On each page, you should also have a (Derived) Class Mapping with Members.  This will necessarily result in a single class being represented across multiple pages.

**Comment by MinZhong7** [comment]
Redesigned each page of Make model. Each Page represents One of the Makes, and on each page, a Derived Class Mapping with Members including Chevrolet, Ford, Honda, Hyundai and Toyota.
